# Generated by Django 4.2.4 on 2023-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_memo', models.TextField(blank=True, verbose_name='Admin Memo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(blank=True)),
                ('humidity', models.FloatField(blank=True)),
                ('bmpTemperature', models.FloatField(blank=True)),
                ('bmpPressure', models.FloatField(blank=True)),
                ('bmpAltitude', models.FloatField(blank=True)),
                ('concentration', models.FloatField(blank=True)),
                ('ugm3', models.FloatField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
